### ISSUE TITLE
drop fields

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript/purescript-record#64] opened 2020-07-22 20:20 UTC
It would be nice to have a function that will drop/delete unnecessary record fields.

`drop :: forall r1 r2. Record r1 -> Record r1` where r2 is a subset of r1

**Comment by garyb** [comment] 2020-07-22 20:25
I think this is a duplicate of #5?

**Comment by JordanMartinez** [comment] 2021-12-04 04:34
Yeah, I'll close this.

**Closed as completed by JordanMartinez** 2021-12-04 04:34 UTC
Labels: duplicate
